-- Seed data from the CSV file
-- First batch of tools
INSERT INTO public.ai_tools (tool_id, app_name, url, short_description, category_1, category_2, category_3, tags, platforms, promo_code, featured_today, sponsored, date_added, last_updated, source_name_or_link)
VALUES
  ('marketing_ai_ads', 'Ai-Ads', 'https://www.adcreative.ai/', 'Generates ad creatives and variations optimized for performance marketing.', 'Design & Branding', 'Revenue (Sales & Commerce)', 'Marketing & SEO', ARRAY['Forms / intake', 'SEO', 'Ads creative'], '', '', FALSE, FALSE, '2026-01-05', '2026-01-05', ''),
  ('prompts_alicent_ai', 'Alicent AI', 'https://alicent.ai/', 'Prompt/workflow helper for generating and organizing prompt templates.', 'Design & Branding', 'Automation & Agents (Workflows)', '', ARRAY['Automation workflows', 'Templates'], '', '', FALSE, FALSE, '2026-01-05', '2026-01-05', ''),
  ('tool_bloggify', 'Bloggify', 'https://bloggify.org/', 'With Bloggify you can build that amazing application you have been dreaming of.', 'Design & Branding', 'Writing & Copywriting', '', ARRAY[]::TEXT[], '', '', FALSE, FALSE, NOW(), NOW(), ''),
  ('chatbot_tool_dante_ai', 'Dante AI', 'https://dante-ai.com/', 'Handle unlimited conversations simultaneously across chat and voice while your team focuses on high-value work.', 'Audio / Voice / Music', 'Chatbots & Assistants', '', ARRAY[]::TEXT[], '', '', FALSE, FALSE, '2026-01-05', '2026-01-05', ''),
  ('image_dalle_3', 'DALL-E 3', 'https://openai.com/index/dall-e-3/', 'Modern text-to-image systems have a tendency to ignore words or descriptions. DALL·E 3 represents a leap forward in our ability to generate images that exactly adhere to the text you provide.', 'Images (Create & Edit)', 'Video (Create & Edit)', 'Audio / Voice / Music', ARRAY['Video editor', 'Image generator'], '', '', TRUE, FALSE, '2026-01-05', '2026-01-05', ''),
  ('tool_dot_ai', 'Dot AI', 'https://dot-ai.app/', 'Stop paying for multiple subscriptions. Access the latest AI models and keep all your conversations in one place.', 'Niche / Other', '', '', ARRAY[]::TEXT[], '', '', FALSE, FALSE, '2026-01-05', '2026-01-05', ''),
  ('image_dreamina_ai', 'Dreamina AI', 'https://dreamina.capcut.com/', 'AI creative suite for generating images and videos from prompts.', 'Design & Branding', 'Video (Create & Edit)', 'Images (Create & Edit)', ARRAY[]::TEXT[], '', '', FALSE, FALSE, '2026-01-05', '2026-01-05', ''),
  ('chatbot_droxy', 'Droxy', 'https://droxy.ai/', 'Create AI chatbots/agents trained on your content for support and sales.', 'Chatbots & Assistants', 'Revenue (Sales & Commerce)', '', ARRAY['Agentic / autonomous', 'Sales outreach'], '', '', FALSE, FALSE, '2026-01-05', '2026-01-05', ''),
  ('image_flux', 'Flux', 'https://bfl.ai/', 'Home site for the FLUX model ecosystem (Black Forest Labs)', 'Images (Create & Edit)', 'Design & Branding', 'Audio / Voice / Music', ARRAY['Image generator'], '', '', FALSE, FALSE, '2026-01-05', '2026-01-05', ''),
  ('productivity_gemini_2_5_flash', 'Google Gemini', 'https://gemini.google.com/', 'Google Gemini is Google''s family of powerful, multimodal AI models and the AI assistant that uses them.', 'Chatbots & Assistants', 'Productivity & Notes', 'Data & Analytics', ARRAY['Mobile app'], '', '', FALSE, FALSE, '2026-01-05', '2026-01-05', ''),
  ('image_gpt_4o', 'ChatGPT', 'https://chatgpt.com/', 'ChatGPT is an advanced AI chatbot from OpenAI that uses large language models.', 'Chatbots & Assistants', 'Research & Knowledge', 'Writing & Copywriting', ARRAY[]::TEXT[], '', '', FALSE, FALSE, '2026-01-05', '2026-01-05', ''),
  ('uiux_instantai', 'InstantAI', 'https://goinstant.ai/', 'Access to ChatGPT, Gemini, Grok, Claude, Perplexity & more for the price of one LLM.', 'Chatbots & Assistants', 'Design & Branding', 'Research & Knowledge', ARRAY['Agentic / autonomous'], '', '', FALSE, FALSE, '2026-01-05', '2026-01-05', ''),
  ('tool_kling_ai', 'Kling AI', 'https://klingai.com/', 'AI video generation platform (text/image to video).', 'Video (Create & Edit)', 'Images (Create & Edit)', 'Docs, Forms & Data Capture', ARRAY['Video generator', 'Forms / intake', 'Image-to-video'], '', '', FALSE, FALSE, NOW(), NOW(), ''),
  ('website_landingsite', 'Landingsite', 'https://landingsite.ai/', 'AI-powered website builder that creates stunning, responsive marketing websites instantly.', 'App & App Builder / Support', 'Design & Branding', 'Coding & Developer Tools', ARRAY[]::TEXT[], '', '', FALSE, FALSE, '2026-01-05', '2026-01-05', ''),
  ('research_otio', 'Otio', 'https://otio.ai/', 'The Fastest Way To Do Research. Understand & chat with your docs, links & videos. Automate complex research workflows with AI', 'Research & Knowledge', 'Video (Create & Edit)', 'Automation & Agents (Workflows)', ARRAY['Automation workflows', 'Summarizer', 'Knowledge base', 'Document / PDF tools'], '', '', FALSE, FALSE, '2026-01-05', '2026-01-05', ''),
  ('resume_resume_ai', 'Resume IO', 'https://resume.io/', 'AI Resume checker', 'HR & Recruiting', '', '', ARRAY[]::TEXT[], '', '', FALSE, FALSE, '2026-01-05', '2026-01-05', ''),
  ('resume_resume_checker', 'AI Apply', 'https://aiapply.co/ai-resume-checker', 'AI Resume checker', 'HR & Recruiting', '', '', ARRAY[]::TEXT[], '', '', FALSE, FALSE, '2026-01-05', '2026-01-05', ''),
  ('research_silatus', 'Silatus', 'https://silatus.framer.website/', 'Privacy-first gen AI research automation and chat.', 'Research & Knowledge', 'Automation & Agents (Workflows)', 'Cybersecurity & Privacy', ARRAY['Data privacy-focused', 'Privacy-first', 'Automation workflows', 'Summarizer', 'Knowledge base'], '', '', FALSE, FALSE, '2026-01-05', '2026-01-05', ''),
  ('audio_songburst_ai', 'Songburst AI', 'https://www.songburst.ai/', 'Generate music with AI. Make music for your online content like videos and podcasts.', 'Audio / Voice / Music', 'App & App Builder / Support', 'Video (Create & Edit)', ARRAY['Mobile app', 'Podcast', 'Music'], '', '', FALSE, FALSE, '2026-01-05', '2026-01-05', ''),
  ('twitter_tweetlify', 'Tweetlify', 'https://tweetlify.vercel.app/', 'AI That Writes Remarkable Tweets!', 'Writing & Copywriting', '', '', ARRAY[]::TEXT[], '', '', FALSE, FALSE, '2026-01-05', '2026-01-05', ''),
  ('uiux_uimagic', 'UiMagic', 'https://uxpilot.ai/ai-ui-generator', 'Create stunning, professional UI designs', 'Design & Branding', '', '', ARRAY[]::TEXT[], '', '', FALSE, FALSE, '2026-01-05', '2026-01-05', ''),
  ('uiux_ux_pilot', 'UX Pilot', 'https://uxpilot.ai/', 'YOUR AI CO-PILOT FOR UX DESIGN', 'Design & Branding', '', '', ARRAY[]::TEXT[], '', '', FALSE, FALSE, '2026-01-05', '2026-01-05', ''),
  ('video_veo_2', 'Google Veo', 'https://deepmind.google/models/veo/', 'Google Veo is a powerful AI model for generating high-quality, 1080p videos from text or image prompts.', 'Video (Create & Edit)', 'Audio / Voice / Music', 'Images (Create & Edit)', ARRAY['Video generator', 'Music', 'Image-to-video'], '', '', FALSE, FALSE, '2026-01-05', '2026-01-05', ''),
  ('tool_vibecoder', 'Vibecoder', 'https://vibecodeapp.com/', 'Create AI apps and websites from your phone (mobile)', 'Coding & Developer Tools', 'Data & Analytics', '', ARRAY[]::TEXT[], '', '', FALSE, FALSE, '2026-01-05', '2026-01-05', ''),
  ('audio_voicemyai', 'VoicemyAI', 'https://voicemy.ai/', 'Create AI voices, compose melodies. Share your passion, inspire the world.', 'Audio / Voice / Music', '', '', ARRAY[]::TEXT[], '', '', FALSE, FALSE, '2026-01-05', '2026-01-05', '')
ON CONFLICT (tool_id) DO NOTHING;
